# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 17:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('blog', '0004_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='image2',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_2', to='filer.Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, related_name='image_1', to='filer.File'),
        ),
    ]
