# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 15:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170509_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='image2',
        ),
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=filer.fields.file.FilerFileField(default=1, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
            preserve_default=False,
        ),
    ]
