# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('blog', '0007_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='desc_1',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='desc_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='desc_3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='news_link_1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='news_link_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='news_link_3',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=filer.fields.file.FilerFileField(default=0, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.News'),
        ),
    ]
