# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170511_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='header',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
